use onlineshop;
delete from customer;
delete from cartitem;
delete from cart;
delete from billing_address;
delete from shipping_address;
delete from salesorder;
delete from authorities;
delete from users;
delete from product;